export const INFECTIOUS_ASSAYS = [
  {
    slug: 'hbv',
    shortName: 'HBV',
    fullName: 'Mugen-Plex HBV Real-Time PCR Assay',
    organism: 'hepatitis B virus',
    researchArea: 'hepatitis B virus research workflows',
    specimen: 'Plasma',
    storage: '2–8 °C',
    formats: '24-, 48-, and 96-test formats',
    color: '#00A3E0',
    image: '/images/infectious/mugen-plex-hbv.png',
    sds: '/sds/Mugen-Plex-HBV-SDS-v1.0.pdf',
  },
  {
    slug: 'hcv',
    shortName: 'HCV',
    fullName: 'Mugen-Plex HCV Real-Time PCR Assay',
    organism: 'hepatitis C virus',
    researchArea: 'hepatitis C virus research workflows',
    specimen: 'Plasma',
    storage: '2–8 °C',
    formats: '24-, 48-, and 96-test formats',
    color: '#5A9B5F',
    image: '/images/infectious/mugen-plex-hcv.png',
    sds: '/sds/Mugen-Plex-HCV-SDS-v1.0.pdf',
  },
  {
    slug: 'hiv',
    shortName: 'HIV',
    fullName: 'Mugen-Plex HIV Real-Time PCR Assay',
    organism: 'human immunodeficiency virus',
    researchArea: 'human immunodeficiency virus research workflows',
    specimen: 'Plasma',
    storage: '2–8 °C',
    formats: '24-, 48-, and 96-test formats',
    color: '#7B61A8',
    image: '/images/infectious/mugen-plex-hiv.png',
    sds: '/sds/Mugen-Plex-HIV-SDS-v1.0.pdf',
  },
  {
    slug: 'dengue-chikungunya',
    shortName: 'Dengue / Chikungunya',
    fullName: 'Mugen-Plex Dengue / Chikungunya Real-Time PCR Assay',
    organism: 'dengue and chikungunya viruses',
    researchArea: 'combined dengue and chikungunya virus research workflows',
    specimen: 'Plasma',
    storage: '2–8 °C',
    formats: '24-, 48-, and 96-test formats',
    color: '#E06F61',
    image: '/images/infectious/mugen-plex-dengue-chikungunya.png',
    sds: '/sds/Mugen-Plex-Dengue-Chikungunya-SDS-v1.0.pdf',
  },
  {
    slug: 'influenza-a-b',
    shortName: 'Influenza A & B',
    fullName: 'Mugen-Plex Influenza A & B Real-Time PCR Assay',
    organism: 'influenza A and influenza B viruses',
    researchArea: 'influenza A and B virus research workflows',
    specimen: 'Nasopharyngeal swab',
    storage: '2–8 °C',
    formats: '24-, 48-, and 96-test formats',
    color: '#159AA3',
    image: '/images/infectious/mugen-plex-influenza-a-b.png',
    sds: '/sds/Mugen-Plex-Influenza-AB-SDS-v1.0.pdf',
  },
  {
    slug: 'cchf',
    shortName: 'CCHF',
    fullName: 'Mugen-Plex CCHF Real-Time PCR Assay',
    organism: 'Crimean-Congo haemorrhagic fever virus',
    researchArea: 'Crimean-Congo haemorrhagic fever virus research workflows',
    specimen: 'Plasma',
    storage: '2–8 °C',
    formats: '24-, 48-, and 96-test formats',
    color: '#D86A2C',
    image: '/images/infectious/mugen-plex-cchf.png',
    sds: '/sds/Mugen-Plex-CCHF-SDS-v1.0.pdf',
  },
];

export function getInfectiousAssay(slug) {
  return INFECTIOUS_ASSAYS.find((assay) => assay.slug === slug);
}
